.TH CLIBASIC 1 "2021-09-09" "0.22"
.SH NAME
CLIBASIC \- Command Line Interface BASIC
.SH SYNOPSIS
\fBclibasic\fR [\fIOPTION\fR]...
.SH DESCRIPTION
A BASIC interpreter for the terminal (or console), written in C
.SH OPTIONS
.PP
.TP 7
\fB\-\-help\fR
Shows the usage and option information.
.TP
\fB\-\-version\fR
Shows the version and license information.
.TP
\fB\-\-args\fR [\fI\,ARG\/\fR]...
Passes ARGs to the program.
.TP
\fB\-x\fR, \fB\-\-exec\fR \fI\,FILE\/\fR [\fI\,ARG\/\fR]...
Runs and passes ARGs to FILE.
.TP
\fB\-f\fR, \fB\-\-file\fR \fI\,FILE\/\fR
Runs FILE.
.TP
\fB\-c\fR, \fB\-\-command\fR \fI\,COMMAND\/\fR
Runs COMMAND and exits.
.TP
\fB\-k\fR, \fB\-\-keep\fR
Stops CLIBASIC from resetting text attributes.
.TP
\fB\-s\fR, \fB\-\-skip\fR
Skips searching for autorun programs.
.TP
\fB\-i\fR, \fB\-\-info\fR
Enables the info text.
.TP
\fB\-r\fR, \fB\-\-redirection\fR
Enables support for redirecting STDIN, STDOUT, and STDERR.
.TP
\fB\-n\fR, \fB\-\-newline\fR
Prints a newline if the cursor is not at the beginning of the line before exiting.
.SH EXAMPLES
.TP
\fBclibasic\fR
Runs CLIBASIC in shell mode.
.TP
\fBclibasic\fR \-i
Runs CLIBASIC in shell mode and displays the info header like earlier versions of CLIBASIC.
.TP
\fBclibasic\fR examples/info.bas
Looks for ./examples/info.bas and if successful, loads and runs the file. CLIBASIC will exit once an error has occurred or execution completes successfully.
.TP
\fBclibasic\fR \-f \-bar\-.bas
In the case you want to run a file that starts with a hyphen, use the \-file or \-f option which will cause the next argument to be evaluated as a file name.
.TP
\fBclibasic\fR \-c 'PRINT "FOO"; "BAR"'
If you want to run a single command, use the \-\-command or \-c option which will interpret the next argument as if it were typed in during shell mode.
.SH EXIT STATUS
.TP
\fB0\fR
Success.
.TP
\fB1\fR
Error occurred.
.TP
\fBNOTE:\fR
Any exit status (0\-255) can be returned by the program or command via the 'EXIT' command.
.SH FILES
.TP
\fB\fI~/.clibasic_history\fR
History file for storing previously entered commands from shell mode.
.SH AUTHOR
.TP
PQCraft <0456523@gmail.com>
.SH COPYRIGHT
Copyright (C) 2021 PQCraft
.br
Licensed under the GNU General Public License version 3.0

